### ISSUE TITLE
LibJS: Derived class methods are undefined when extending `EventTarget`

### ISSUE THREAD

**Issue by tcl3** [LadybirdBrowser/ladybird#334]
Given the following reduction:
```html
<script>
class X extends EventTarget {
    foo() {
        console.log("hi!");
    }
}
new X().foo();
</script>
```

We currently get the following JS error:
```
Unhandled JavaScript exception: [TypeError] undefined is not a function (evaluated from '<object>.foo')
     at file:///home/tim/ladybird-stuff/extend-eventtarget.html:7:1
```

Bisected to: f28bb90d9bd6c65cde25c3044e29e75879d4348. Reverting this commit makes the above reduction work as expected.

CC: @shannonbooth

**Comment by caitp** [comment]
this is probably a problem for most/all DOM interfaces -- the bindings is generating code to invoke Class::construct_impl(), which performs the allocation of the resulting object -- but ignores (and does not pass on) the new_target parameter, so the C constructor is completely oblivious to a new.target which is distinct from the class itself. I think the DOM bindings gen needs some work to emit constructor implementations that are aware of the JS new.target

**Comment by tcl3** [comment]
Fixed by #379
