### PR TITLE
Meta: Add vulkan and vulkan-headers to vcpkg dependencies

### LINKED ISSUE #444: Introduction of Skia Vulkan backend breaks build in  Ubuntu 22.04.4 LTS/Jammy (on WSL2)
With https://github.com/LadybirdBrowser/ladybird/commit/e713de115c394480b7d57653fe7b472db0dc7ce3, the compilation of DisplayListPlayerSkia.cpp fails with the errors;

```
In file included from /src/ladybird/Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp:31:
In file included from /src/ladybird/Build/ladybird/vcpkg_installed/x64-linux/include/skia/gpu/vk/GrVkBackendContext.h:12:
In file included from /src/ladybird/Build/ladybird/vcpkg_installed/x64-linux/include/skia/include/gpu/vk/GrVkTypes.h:13:
/src/ladybird/Build/ladybird/vcpkg_installed/x64-linux/include/skia/include/gpu/vk/VulkanTypes.h:107:56: error: use of undeclared identifier 'VkDeviceFaultAddressInfoEXT'
  107 |                                      const std::vector<VkDeviceFaultAddressInfoEXT>& addressInfos,
      |                                                        ^
/src/ladybird/Build/ladybird/vcpkg_installed/x64-linux/include/skia/include/gpu/vk/VulkanTypes.h:108:56: error: use of undeclared identifier 'VkDeviceFaultVendorInfoEXT'
  108 |                                      const std::vector<VkDeviceFaultVendorInfoEXT>& vendorInfos,
      |                                                        ^
```

Evaluating with -E, I see vulkan_core.h get pulled in by LibCore/VulkanContext.h, and it seems to grab the system installed version in /usr/include/vulkan -- This is from the system wide package libvulkan-dev @1.3.204.1-2 -- and does not include the VkDeviceFaultAddressInfoEXT definition.

So, we probably don't want to mix and match system vulkan and skia vulkan, it seems like ideally they'd both use the same version.

### PR DESCRIPTION
**Pull request by ADKaster**
Also require a specific ICU version to not run into unexpected problems.

Fixes #444

### CODE REVIEW

File: .github/actions/setup/action.yml [hunk 1]
```diff
@@ -25,7 +25,9 @@ runs:
         sudo add-apt-repository ppa:ubuntu-toolchain-r/test
 
         sudo apt-get update
-        sudo apt-get install autoconf autoconf-archive automake build-essential cmake libavcodec-dev fonts-liberation2 zip curl tar ccache clang-18 clang++-18 lld-18 gcc-13 g++-13 libstdc++-13-dev ninja-build unzip qt6-base-dev qt6-tools-dev-tools libqt6svg6-dev qt6-multimedia-dev libgl1-mesa-dev libpulse-dev libssl-dev libegl1-mesa-dev
+        sudo apt-get install autoconf autoconf-archive automake build-essential cmake libavcodec-dev fonts-liberation2 zip curl tar ccache clang-18 clang++-18 lld-18 gcc-13 g++-13 libstdc++-13-dev \
+            ninja-build unzip qt6-base-dev qt6-tools-dev-tools libqt6svg6-dev qt6-multimedia-dev libgl1-mesa-dev libpulse-dev libssl-dev libegl1-mesa-dev \
+            libx11-dev libxrandr-dev
```
Comment (ADKaster) [inline .github/actions/setup/action.yml:30]: Not happy about these new deps. Feels gross to need both x11 and Wayland headers, regardless of what your distro is.

But, without pulling vulkan-headers and vulkan from vcpkg, developers who have Vulkan development libs on their system run into header-mixing problems anyway. Since skia will be pulling vulkan from vcpkg, and LibCore would be pulling it from your system.

:T

**Review by kalenikaliaksandr — APPROVED** [review]
