### ISSUE TITLE
Introduction of Skia Vulkan backend breaks build in  Ubuntu 22.04.4 LTS/Jammy (on WSL2)

### ISSUE THREAD

**Issue by caitp** [LadybirdBrowser/ladybird#444]
With https://github.com/LadybirdBrowser/ladybird/commit/e713de115c394480b7d57653fe7b472db0dc7ce3, the compilation of DisplayListPlayerSkia.cpp fails with the errors;

```
In file included from /src/ladybird/Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp:31:
In file included from /src/ladybird/Build/ladybird/vcpkg_installed/x64-linux/include/skia/gpu/vk/GrVkBackendContext.h:12:
In file included from /src/ladybird/Build/ladybird/vcpkg_installed/x64-linux/include/skia/include/gpu/vk/GrVkTypes.h:13:
/src/ladybird/Build/ladybird/vcpkg_installed/x64-linux/include/skia/include/gpu/vk/VulkanTypes.h:107:56: error: use of undeclared identifier 'VkDeviceFaultAddressInfoEXT'
  107 |                                      const std::vector<VkDeviceFaultAddressInfoEXT>& addressInfos,
      |                                                        ^
/src/ladybird/Build/ladybird/vcpkg_installed/x64-linux/include/skia/include/gpu/vk/VulkanTypes.h:108:56: error: use of undeclared identifier 'VkDeviceFaultVendorInfoEXT'
  108 |                                      const std::vector<VkDeviceFaultVendorInfoEXT>& vendorInfos,
      |                                                        ^
```

Evaluating with -E, I see vulkan_core.h get pulled in by LibCore/VulkanContext.h, and it seems to grab the system installed version in /usr/include/vulkan -- This is from the system wide package libvulkan-dev @1.3.204.1-2 -- and does not include the VkDeviceFaultAddressInfoEXT definition.

So, we probably don't want to mix and match system vulkan and skia vulkan, it seems like ideally they'd both use the same version.

**Comment by ADKaster** [comment]
@kalenikaliaksandr This looks odd. Are we sure that the Skia from vcpkg includes all the files we need, or were you accidentally also using system headers?
