### PR TITLE
Meta: Accept `-j` wherever may reach a build step in ladybird.py

### LINKED ISSUE #9047: ladybird.py: AttributeError: 'Namespace' object has no attribute 'jobs'
### Summary

Broken by 71d1b92eb42194851537b3c8bb7232033bc9103b

```sh
$ Meta/ladybird.py vcpkg
  Traceback (most recent call last):
    File "/src/Meta/ladybird.py", line 486, in <module>
      main()
      ~~~~^^
    File "/src/Meta/ladybird.py", line 145, in main
      if args.jobs:
         ^^^^^^^^^
  AttributeError: 'Namespace' object has no attribute 'jobs'
```

### Operating system

Linux

### Steps to reproduce

1.
2.
3.

### Expected behavior

Should work

### Actual behavior

Broken

### URL for a reduced test case

N/A

### HTML/SVG/etc. source for a reduced test case

```html
N/A
```

### Log output and (if possible) backtrace

```shell
N/A
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by alimpfard**
...and skip checking it in cases that don't.
Fixes #9047.

Sorry, this whole subparser thing is news to me :sweat_smile:

### CODE REVIEW

**Comment by ivankra** [comment]
Why do all subcommands have to take that flag if it only affects vcpkg? Are you planning to extend it beyond vcpkg? What was the problem you were trying to solve?

File: Meta/ladybird.py [hunk 1]
```diff
@@ -142,7 +152,7 @@ def main():
         if not args.target and args.command not in ("build", "rebuild"):
             args.target = "ladybird" if platform.host_system == HostSystem.Windows else "Ladybird"
 
-    if args.jobs:
+    if "jobs" in args and args.jobs:
```
Comment (ivankra) [inline Meta/ladybird.py]: While `"jobs" in args` seems to work for `argparse.Namespace` because it *happens* to override `__contains__`, the correct way in general to test whether you can do `args.jobs` is `hasattr(args, "jobs")`.

**Comment by alimpfard** [comment]
> Why do all subcommands have to take that flag if it only affects vcpkg?

Because all the subcommands taking that flag have a step that ends up in vcpkg.

File: Meta/ladybird.py (hunk 1 above)
Comment (alimpfard) [reply Meta/ladybird.py]: The rest of the file does `in` also :shrug:
https://github.com/LadybirdBrowser/ladybird/blob/64938e257af36e77a809f955ddb86cc93e40f204/Meta/ladybird.py#L139

File: Meta/ladybird.py [hunk 2]
```diff
@@ -40,10 +40,12 @@ def main():
         default=os.environ.get("BUILD_PRESET", "Release"),
     )
 
+    any_build_parser = argparse.ArgumentParser(add_help=False)
+    any_build_parser.add_argument("--jobs", "-j", required=False)
```
Comment (trflynn89) [inline Meta/ladybird.py]: Does the following patch (on top of `master`) work for you? I'd rather we pass the `jobs` flag down to where we set all other vcpkg environment variables:

```diff
diff --git a/Meta/ladybird.py b/Meta/ladybird.py
index 7a27c731cf..ce94a98bf8 100755
--- a/Meta/ladybird.py
+++ b/Meta/ladybird.py
@@ -102,7 +102,10 @@ def main():
         "args", nargs=argparse.REMAINDER, help="Additional arguments passed through to the build system"
     )

-    subparsers.add_parser("vcpkg", help="Ensure that dependencies are available", parents=[preset_parser])
+    vcpkg_parser = subparsers.add_parser(
+        "vcpkg", help="Ensure that dependencies are available", parents=[preset_parser]
+    )
+    vcpkg_parser.add_argument("--jobs", "-j", required=False)

     subparsers.add_parser("clean", help="Cleans the build environment", parents=[preset_parser])

@@ -142,14 +145,11 @@ def main():
         if not args.target and args.command not in ("build", "rebuild"):
             args.target = "ladybird" if platform.host_system == HostSystem.Windows else "Ladybird"

-    if args.jobs:
-        os.environ["VCPKG_MAX_CONCURRENCY"] = args.jobs
-
     if args.command == "build":
-        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.gui)
+        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.jobs, args.gui)
         build_main(build_dir, args.jobs, args.target, args.args)
     elif args.command == "test":
-        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.gui)
+        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.jobs, args.gui)
         build_main(build_dir, args.jobs)
         test_main(build_dir, args.preset, args.pattern)
     elif args.command == "run":
@@ -163,38 +163,40 @@ def main():
             os.environ["UBSAN_OPTIONS"] = os.environ.get(
                 "UBSAN_OPTIONS", "print_stacktrace=1:print_summary=1:halt_on_error=1"
             )
-        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.gui)
+        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.jobs, args.gui)
         build_main(build_dir, args.jobs, args.target)
         run_main(platform.host_system, build_dir, args.target, args.args)
     elif args.command == "debug":
-        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.gui)
+        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.jobs, args.gui)
         build_main(build_dir, args.jobs, args.target, args.args)
         debug_main(platform.host_system, build_dir, args.target, args.debugger, args.cmd)
     elif args.command == "profile":
-        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.gui)
+        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.jobs, args.gui)
         build_main(build_dir, args.jobs, args.target)
         profile_main(platform.host_system, build_dir, args.target, args.args)
     elif args.command == "install":
-        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.gui)
+        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.jobs, args.gui)
         build_main(build_dir, args.jobs, args.target, args.args)
         build_main(build_dir, args.jobs, "install", args.args)
     elif args.command == "vcpkg":
-        configure_build_env(platform, args.preset)
+        configure_build_env(platform, args.preset, args.jobs)
         build_vcpkg()
     elif args.command == "clean":
         clean_main(platform, args.preset)
     elif args.command == "rebuild":
         clean_main(platform, args.preset)
-        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.gui)
+        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.jobs, args.gui)
         build_main(build_dir, args.jobs, args.target, args.args)
     elif args.command == "addr2line":
-        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.gui)
+        build_dir = configure_main(platform, args.preset, args.cc, args.cxx, args.jobs, args.gui)
         build_main(build_dir, args.jobs, args.target)
         addr2line_main(build_dir, args.target, args.program, args.addresses)


-def configure_main(platform: Platform, preset: str, cc: str, cxx: str, gui: Optional[GUIFramework]) -> Path:
-    ladybird_source_dir, build_preset_dir = configure_build_env(platform, preset)
+def configure_main(
+    platform: Platform, preset: str, cc: str, cxx: str, jobs: Optional[str], gui: Optional[GUIFramework]
+) -> Path:
+    ladybird_source_dir, build_preset_dir = configure_build_env(platform, preset, jobs)
     build_vcpkg()

     if build_preset_dir.joinpath("build.ninja").exists() or build_preset_dir.joinpath("ladybird.sln").exists():
@@ -281,7 +283,7 @@ def configure_skia_jemalloc() -> list[str]:
     return cmake_args


-def configure_build_env(platform: Platform, preset: str) -> tuple[Path, Path]:
+def configure_build_env(platform: Platform, preset: str, jobs: Optional[str] = None) -> tuple[Path, Path]:
     ladybird_source_dir = ensure_ladybird_source_dir()
     build_root_dir = ladybird_source_dir / "Build"

@@ -302,6 +304,10 @@ def configure_build_env(platform: Platform, preset: str) -> tuple[Path, Path]:
     vcpkg_root = str(build_root_dir / "vcpkg")
     os.environ["PATH"] += os.pathsep + vcpkg_root
     os.environ["VCPKG_ROOT"] = vcpkg_root
+
+    if jobs:
+        os.environ["VCPKG_MAX_CONCURRENCY"] = jobs
+
     if platform.host_architecture == HostArchitecture.riscv64:
         # vcpkg refuses to build ports on riscv64 and other less common architectures without this flag.
         # With it set vcpkg will use the system provided CMake and Ninja binaries but will still download,
```

Comment (alimpfard) [reply Meta/ladybird.py]: Seems to work fine yeah.
wanna PR it or should I replace this PR with that?

Comment (trflynn89) [reply Meta/ladybird.py]: feel free to yoink it!

**Review by trflynn89 — APPROVED** [review]
