### ISSUE TITLE
ladybird.py: AttributeError: 'Namespace' object has no attribute 'jobs'

### ISSUE THREAD

**Issue by ivankra** [LadybirdBrowser/ladybird#9047]
### Summary

Broken by 71d1b92eb42194851537b3c8bb7232033bc9103b

```sh
$ Meta/ladybird.py vcpkg
  Traceback (most recent call last):
    File "/src/Meta/ladybird.py", line 486, in <module>
      main()
      ~~~~^^
    File "/src/Meta/ladybird.py", line 145, in main
      if args.jobs:
         ^^^^^^^^^
  AttributeError: 'Namespace' object has no attribute 'jobs'
```

### Operating system

Linux

### Steps to reproduce

1.
2.
3.

### Expected behavior

Should work

### Actual behavior

Broken

### URL for a reduced test case

N/A

### HTML/SVG/etc. source for a reduced test case

```html
N/A
```

### Log output and (if possible) backtrace

```shell
N/A
```

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

**Comment by ivankra** [comment]
@alimpfard @gmta
